events {}

http {

  upstream academic_service {
      server academic-service:3003;
  }

  upstream learning_service {
      server learning-service:3006;
  }

  upstream student_service {
      server student-service:3008;
  }

  server {

    listen 80;

    location /academic/ {
        proxy_pass http://academic_service/;
    }

    location /learning/ {
        proxy_pass http://learning_service/;
    }

    location /student/ {
        proxy_pass http://student_service/;
    }

  }

}