-- student-service tidak memiliki tabel sendiri.
-- Data user/akun dikelola oleh Keycloak (auth-service).
-- Tabel wali kelas (kebersihan_kelas, parenting_log, refleksi_wali_kelas)
-- ada di academic-service, bukan di sini.