name: CI Absensi Siswa Academic - Gloria 11S23030

on:
  push:
    # Menambahkan branch main dan master agar tetap jalan setelah merge
    branches: ["main", "master", "crud-absensi-siswa"]
  pull_request:
    # Menjalankan tes saat ada pengajuan gabung kode (Pull Request)
    branches: ["main", "master"]

jobs:
  test-absensi:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/academic-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./backend/academic-service/package-lock.json"

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Testing
        run: npx jest src/controllers/absensiSiswa.test.js